--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Debian 17.4-1.pgdg120+2)
-- Dumped by pg_dump version 17.4 (Debian 17.4-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: db-forms; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "db-forms" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE "db-forms" OWNER TO postgres;

\encoding SQL_ASCII
\connect -reuse-previous=on "dbname='db-forms'"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;


CREATE TABLE public.etapa (
    id bigint NOT NULL,
    descricao text,
    titulo character varying(255),
    formulario_id bigint
);


ALTER TABLE public.etapa OWNER TO postgres;



ALTER TABLE public.etapa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.etapa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.formulario (
    id bigint NOT NULL,
    descricao character varying(255),
    tipo character varying(255),
    titulo character varying(255)
);


ALTER TABLE public.formulario OWNER TO postgres;


ALTER TABLE public.formulario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.formulario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.pergunta (
    id bigint NOT NULL,
    texto character varying(255),
    tipo character varying(255),
    max bigint,
    min bigint,
    required boolean,
    etapa_id bigint
);


ALTER TABLE public.pergunta OWNER TO postgres;

ALTER TABLE public.pergunta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pergunta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




ALTER TABLE ONLY public.etapa
    ADD CONSTRAINT etapa_pkey PRIMARY KEY (id);




ALTER TABLE ONLY public.formulario
    ADD CONSTRAINT formulario_pkey PRIMARY KEY (id);




ALTER TABLE ONLY public.pergunta
    ADD CONSTRAINT pergunta_pkey PRIMARY KEY (id);




ALTER TABLE ONLY public.pergunta
    ADD CONSTRAINT fkbfratvs2de682msn4dj0phs7x FOREIGN KEY (etapa_id) REFERENCES public.etapa(id);




ALTER TABLE ONLY public.etapa
    ADD CONSTRAINT fkror1pdclr3mnr3f61wcurp8xe FOREIGN KEY (formulario_id) REFERENCES public.formulario(id);




