--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Debian 17.4-1.pgdg120+2)
-- Dumped by pg_dump version 17.4 (Debian 17.4-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: db-pacientes; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "db-pacientes" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE "db-pacientes" OWNER TO postgres;

\encoding SQL_ASCII
\connect -reuse-previous=on "dbname='db-pacientes'"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: paciente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.paciente (
    id bigint NOT NULL,
    cpf character varying(255) NOT NULL,
    data_nasc character varying(255),
    bairro character varying(255),
    cep character varying(255),
    complemento character varying(255),
    logradouro character varying(255),
    municipio character varying(255),
    numero integer,
    uf character varying(255),
    idade integer,
    nome character varying(255) NOT NULL,
    password_hash character varying(255),
    salt character varying(255),
    senha character varying(255),
    sexo character varying(255) NOT NULL,
    telefone character varying(255),
    altura real NOT NULL,
    cor_raca character varying(255),
    data_expedicao character varying(255),
    escolaridade character varying(255),
    estado_civil character varying(255),
    imc real,
    municipio_nasc character varying(255),
    nacionalidade character varying(255),
    orgao_emissor character varying(255),
    peso real NOT NULL,
    rg character varying(255),
    socioeconomico character varying(255),
    uf_emissor character varying(255),
    uf_nasc character varying(255),
    version bigint
);


ALTER TABLE public.paciente OWNER TO postgres;

--
-- Name: paciente_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.paciente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.paciente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: paciente paciente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.paciente
    ADD CONSTRAINT paciente_pkey PRIMARY KEY (id);


--
-- Name: paciente ukfvlo8m5kqpr7knbyw4rjyer2s; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.paciente
    ADD CONSTRAINT ukfvlo8m5kqpr7knbyw4rjyer2s UNIQUE (cpf);


--
-- PostgreSQL database dump complete
--

