--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Debian 17.4-1.pgdg120+2)
-- Dumped by pg_dump version 17.4 (Debian 17.4-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: db-tecnicos; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "db-tecnicos" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE "db-tecnicos" OWNER TO postgres;

\encoding SQL_ASCII
\connect -reuse-previous=on "dbname='db-tecnicos'"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: tecnico; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tecnico (
    id bigint NOT NULL,
    cpf character varying(255) NOT NULL,
    data_nasc character varying(255),
    bairro character varying(255),
    cep character varying(255),
    complemento character varying(255),
    logradouro character varying(255),
    municipio character varying(255),
    numero integer,
    uf character varying(255),
    idade integer,
    nome character varying(255) NOT NULL,
    password_hash character varying(255),
    salt character varying(255),
    senha character varying(255),
    sexo character varying(255) NOT NULL,
    telefone character varying(255),
    ativo boolean,
    matricula character varying(255)
);


ALTER TABLE public.tecnico OWNER TO postgres;

--
-- Name: tecnico_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tecnico ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tecnico_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tecnico tecnico_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tecnico
    ADD CONSTRAINT tecnico_pkey PRIMARY KEY (id);


--
-- Name: tecnico ukcecbp9mq0y2qh6r4j6m8lc36a; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tecnico
    ADD CONSTRAINT ukcecbp9mq0y2qh6r4j6m8lc36a UNIQUE (cpf);


--
-- PostgreSQL database dump complete
--

